export const logos = [
  {
    src: "/icons/html-5.svg",
    alt: "HTML",
    title: "HTML",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    src: "/icons/css-3.svg",
    alt: "CSS3",
    title: "CSS3",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  {
    src: "/icons/js.svg",
    alt: "JavaScript",
    title: "JavaScript",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  {
    src: "/icons/react.svg",
    alt: "React",
    title: "React",
    link: "https://reactjs.org/",
  },
  {
    src: "/icons/next.webp",
    alt: "Next.js",
    title: "Next.js",
    link: "https://nextjs.org/",
  },
  {
    src: "/icons/node.png",
    alt: "Node.js",
    title: "Node.js",
    link: "https://nodejs.org/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
    alt: "Express.js",
    title: "Express.js",
    link: "https://expressjs.com/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
    alt: "MongoDB",
    title: "MongoDB",
    link: "https://www.mongodb.com/",
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg",
    alt: "Tailwind CSS",
    title: "Tailwind CSS",
    link: "https://tailwindcss.com/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg",
    alt: "Apollo Client",
    title: "Apollo Client",
    link: "https://www.apollographql.com/docs/react/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
    alt: "Git",
    title: "Git",
    link: "https://git-scm.com/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
    alt: "GitHub",
    title: "GitHub",
    link: "https://github.com/",
  },
];
export const tools = [
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg",
    alt: "Redux",
    title: "Redux",
    link: "https://redux.js.org/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
    alt: "TypeScript",
    title: "TypeScript",
    link: "https://www.typescriptlang.org/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg",
    alt: "NPM",
    title: "NPM",
    link: "https://www.npmjs.com/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/yarn/yarn-original.svg",
    alt: "Yarn",
    title: "Yarn",
    link: "https://yarnpkg.com/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webpack/webpack-original.svg",
    alt: "Webpack",
    title: "Webpack",
    link: "https://webpack.js.org/",
  },

  {
    src: "https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/postman-icon.svg",
    alt: "Postman",
    title: "Postman",
    link: "https://www.postman.com/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/heroku/heroku-original.svg",
    alt: "Heroku",
    title: "Heroku",
    link: "https://www.heroku.com/",
  },
  {
    src: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico",
    alt: "Vercel",
    title: "Vercel",
    link: "https://vercel.com/",
  },
  {
    src: "https://media.licdn.com/dms/image/v2/D4E0BAQGGDoFoqHtOvA/company-logo_200_200/company-logo_200_200/0/1702595267620/renderco_logo?e=2147483647&v=beta&t=ZYrxKUyruOEupgw5Lr5amgwgBCJq8VXH8r05Qr5CeQc",
    alt: "Render",
    title: "Render",
    link: "https://render.com/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg",
    alt: "Firebase",
    title: "Firebase",
    link: "https://firebase.google.com/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg",
    alt: "Jest",
    title: "Jest",
    link: "https://jestjs.io/",
  },
  {
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/eslint/eslint-original.svg",
    alt: "ESLint",
    title: "ESLint",
    link: "https://eslint.org/",
  },
  {
    src: "https://prettier.io/icon.png",
    alt: "Prettier",
    title: "Prettier",
    link: "https://prettier.io/",
  },
];
